### PR TITLE
update 19.05.21

### PR DESCRIPTION
**Pull request by azuenko**
Updated stencils

Original eps zip: https://d1.awsstatic.com/webteam/architecture-icons/AWS-Architecture-Icons_EPS_20190521.f77c8509c6bbaa17b8e508e11b507198d72d2f0b.zip

### CODE REVIEW

**Comment by davidfsmith** [comment]
Thanks for the PR - I’ll take a quick look through Friday morning (UK) and then merge in ;-)

**Comment by davidfsmith** [comment]
Thanks for taking the time to update the stencils with the latest set of service icons.

Are you able to update the stencils with the following to match the previous set:
* Service name for each icon
* Link to the documentation for each service
* Connections - 8 magnets for connecting to other objects

I'll do a quick look to see how many new service icons there are, as it might be faster to quickly update the existing set with any additions from the new .zip

**Comment by azuenko** [comment]
Yeah, thanks for indicating that. I actually didn't know there's some metadata coming with stencils. Till I switched to 'view as a list'. 😝

I looked at `data.plist`, it looks pretty straightforward. I guess you have some ideas to auto-generate it from the bunch of pdf files. Give me some time till the end of this week, I'll probably write a script that does that. 

Did you put the link to the documentation manually, stencil per stencil, or there's a file or something that you used to extract it?

**Comment by davidfsmith** [comment]
I had a look at automating the .plist file stuff, but I couldn't get the Python library I was going to use to work with the Omnigraffle files.  In the end just did the whole lot manually over a weekend with a view to coming back to it at some point - sadly not done that yet.

**Comment by azuenko** [comment]
Hello,

I've updated the stencils. I've also added the script that takes unpacked AWS icons folder and produces the stencils without doing anything by hand. URLs and names are taken from `meta.txt` file, which is matched against filenames.

@davidfsmith could you check, please?

**Comment by davidfsmith** [comment]
Awesome work, I’ll take a look over the weekend

**Comment by davidfsmith** [comment]
All looks good, I've merged it in, corrected a typo in the `convert.sh` and also updated the README, finally I removed the Feb icon set.

Thanks for your effort on this, much appreciated.

**Pull request merged**
